[package]
name = "othello"
version = "0.1.0"
authors = ["uhyo <uhyo@uhy.ooo>"]

[dependencies]
rand = "0.3"
getopts = "0.2"
regex = "0.2"
lazy_static = "0.2.8"
log = "0.3.8"
pretty_env_logger = "0.1.1"
